/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedAreasRouteImport } from './routes/_authenticated/areas'
import { Route as AuthenticatedHistoricoRouteImport } from './routes/_authenticated/historico'
import { Route as AuthenticatedImportarExportarRouteImport } from './routes/_authenticated/importar-exportar'
import { Route as AuthenticatedOrganogramaRouteImport } from './routes/_authenticated/organograma'
import { Route as AuthenticatedPessoasCargosRouteImport } from './routes/_authenticated/pessoas-cargos'
import { Route as AuthenticatedTiposColaboradoresRouteImport } from './routes/_authenticated/tipos-colaboradores'
import { Route as AuthenticatedVisaoGeralRouteImport } from './routes/_authenticated/visao-geral'
import { Route as ColaboradorIdRouteImport } from './routes/colaborador.$id'

const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAreasRoute = AuthenticatedAreasRouteImport.update({
  id: '/areas',
  path: '/areas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoricoRoute = AuthenticatedHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedImportarExportarRoute =
  AuthenticatedImportarExportarRouteImport.update({
    id: '/importar-exportar',
    path: '/importar-exportar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrganogramaRoute =
  AuthenticatedOrganogramaRouteImport.update({
    id: '/organograma',
    path: '/organograma',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPessoasCargosRoute =
  AuthenticatedPessoasCargosRouteImport.update({
    id: '/pessoas-cargos',
    path: '/pessoas-cargos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTiposColaboradoresRoute =
  AuthenticatedTiposColaboradoresRouteImport.update({
    id: '/tipos-colaboradores',
    path: '/tipos-colaboradores',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVisaoGeralRoute = AuthenticatedVisaoGeralRouteImport.update({
  id: '/visao-geral',
  path: '/visao-geral',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ColaboradorIdRoute = ColaboradorIdRouteImport.update({
  id: '/colaborador/$id',
  path: '/colaborador/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/$': typeof SplatRoute
  '/login': typeof LoginRoute
  '/areas': typeof AuthenticatedAreasRoute
  '/historico': typeof AuthenticatedHistoricoRoute
  '/importar-exportar': typeof AuthenticatedImportarExportarRoute
  '/organograma': typeof AuthenticatedOrganogramaRoute
  '/pessoas-cargos': typeof AuthenticatedPessoasCargosRoute
  '/tipos-colaboradores': typeof AuthenticatedTiposColaboradoresRoute
  '/visao-geral': typeof AuthenticatedVisaoGeralRoute
  '/colaborador/$id': typeof ColaboradorIdRoute
}
export interface FileRoutesByTo {
  '/$': typeof SplatRoute
  '/login': typeof LoginRoute
  '/areas': typeof AuthenticatedAreasRoute
  '/historico': typeof AuthenticatedHistoricoRoute
  '/importar-exportar': typeof AuthenticatedImportarExportarRoute
  '/organograma': typeof AuthenticatedOrganogramaRoute
  '/pessoas-cargos': typeof AuthenticatedPessoasCargosRoute
  '/tipos-colaboradores': typeof AuthenticatedTiposColaboradoresRoute
  '/visao-geral': typeof AuthenticatedVisaoGeralRoute
  '/colaborador/$id': typeof ColaboradorIdRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/login': typeof LoginRoute
  '/_authenticated/areas': typeof AuthenticatedAreasRoute
  '/_authenticated/historico': typeof AuthenticatedHistoricoRoute
  '/_authenticated/importar-exportar': typeof AuthenticatedImportarExportarRoute
  '/_authenticated/organograma': typeof AuthenticatedOrganogramaRoute
  '/_authenticated/pessoas-cargos': typeof AuthenticatedPessoasCargosRoute
  '/_authenticated/tipos-colaboradores': typeof AuthenticatedTiposColaboradoresRoute
  '/_authenticated/visao-geral': typeof AuthenticatedVisaoGeralRoute
  '/colaborador/$id': typeof ColaboradorIdRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/login'
    | '/areas'
    | '/historico'
    | '/importar-exportar'
    | '/organograma'
    | '/pessoas-cargos'
    | '/tipos-colaboradores'
    | '/visao-geral'
    | '/colaborador/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$'
    | '/login'
    | '/areas'
    | '/historico'
    | '/importar-exportar'
    | '/organograma'
    | '/pessoas-cargos'
    | '/tipos-colaboradores'
    | '/visao-geral'
    | '/colaborador/$id'
    | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/$'
    | '/login'
    | '/_authenticated/areas'
    | '/_authenticated/historico'
    | '/_authenticated/importar-exportar'
    | '/_authenticated/organograma'
    | '/_authenticated/pessoas-cargos'
    | '/_authenticated/tipos-colaboradores'
    | '/_authenticated/visao-geral'
    | '/colaborador/$id'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  SplatRoute: typeof SplatRoute
  LoginRoute: typeof LoginRoute
  ColaboradorIdRoute: typeof ColaboradorIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/areas': {
      id: '/_authenticated/areas'
      path: '/areas'
      fullPath: '/areas'
      preLoaderRoute: typeof AuthenticatedAreasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/historico': {
      id: '/_authenticated/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof AuthenticatedHistoricoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/importar-exportar': {
      id: '/_authenticated/importar-exportar'
      path: '/importar-exportar'
      fullPath: '/importar-exportar'
      preLoaderRoute: typeof AuthenticatedImportarExportarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/organograma': {
      id: '/_authenticated/organograma'
      path: '/organograma'
      fullPath: '/organograma'
      preLoaderRoute: typeof AuthenticatedOrganogramaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pessoas-cargos': {
      id: '/_authenticated/pessoas-cargos'
      path: '/pessoas-cargos'
      fullPath: '/pessoas-cargos'
      preLoaderRoute: typeof AuthenticatedPessoasCargosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tipos-colaboradores': {
      id: '/_authenticated/tipos-colaboradores'
      path: '/tipos-colaboradores'
      fullPath: '/tipos-colaboradores'
      preLoaderRoute: typeof AuthenticatedTiposColaboradoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/visao-geral': {
      id: '/_authenticated/visao-geral'
      path: '/visao-geral'
      fullPath: '/visao-geral'
      preLoaderRoute: typeof AuthenticatedVisaoGeralRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/colaborador/$id': {
      id: '/colaborador/$id'
      path: '/colaborador/$id'
      fullPath: '/colaborador/$id'
      preLoaderRoute: typeof ColaboradorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAreasRoute: typeof AuthenticatedAreasRoute
  AuthenticatedHistoricoRoute: typeof AuthenticatedHistoricoRoute
  AuthenticatedImportarExportarRoute: typeof AuthenticatedImportarExportarRoute
  AuthenticatedOrganogramaRoute: typeof AuthenticatedOrganogramaRoute
  AuthenticatedPessoasCargosRoute: typeof AuthenticatedPessoasCargosRoute
  AuthenticatedTiposColaboradoresRoute: typeof AuthenticatedTiposColaboradoresRoute
  AuthenticatedVisaoGeralRoute: typeof AuthenticatedVisaoGeralRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAreasRoute: AuthenticatedAreasRoute,
  AuthenticatedHistoricoRoute: AuthenticatedHistoricoRoute,
  AuthenticatedImportarExportarRoute: AuthenticatedImportarExportarRoute,
  AuthenticatedOrganogramaRoute: AuthenticatedOrganogramaRoute,
  AuthenticatedPessoasCargosRoute: AuthenticatedPessoasCargosRoute,
  AuthenticatedTiposColaboradoresRoute: AuthenticatedTiposColaboradoresRoute,
  AuthenticatedVisaoGeralRoute: AuthenticatedVisaoGeralRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  SplatRoute: SplatRoute,
  LoginRoute: LoginRoute,
  ColaboradorIdRoute: ColaboradorIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
